### ISSUE TITLE
Is nightly still required?

### ISSUE THREAD

**Issue by thedodd** [utkarshkukreti/speculate.rs#18]
After reviewing #8 (about 5 months old), looks like this crate was cut over to proc-macro system. As proc-macro has recently stabilized, I figured I would ask.

**Comment by palfrey** [comment]
So, this got mostly fixed by #19 but the README still refers to nightly being needed.

**Comment by utkarshkukreti** [comment]
@palfrey, thanks for pointing that out. I've removed the nightly note!
