### ISSUE TITLE
rustfmt doesn't seem to format the body of `speculate!`

### ISSUE THREAD

**Issue by jacobdeichert** [utkarshkukreti/speculate.rs#28]
First off, thanks for making this! I'm just getting started with testing in rust and this is exactly what I was looking for. 🙂 

Seemingly, rustfmt refuses to format the code inside the `speculate!` macro. I haven't used macros much before, so I wanted to check here first before I post an issue to rustfmt.

Do you know of a way to get rustfmt to work correctly with this framework?

If not, please close and i'll create an issue on rustfmt's repo instead.

**Here's a small example I'm trying to get to work:**

```rust
use speculate::speculate;

// This formats correctly
fn add(a: i32, b: i32) -> i32 {
    a + b
}

speculate! {
// Nothing in here formats correctly
        describe "add" {
            test "adds numbers correctly" {
                    assert_eq!(add(1,2), 3);
                }
    }
}
```

**Expected format:**

```rust
use speculate::speculate;

fn add(a: i32, b: i32) -> i32 {
    a + b
}

speculate! {
    describe "add" {
        test "adds numbers correctly" {
            assert_eq!(add(1,2), 3);
        }
    }
}
```

Thanks for taking the time to read.

**Comment by isomorpheme** [comment]
I'm not a contributor to this project, but I think I can tell you why rustfmt won't touch your tests: macros can have basically any syntax, so rustfmt cannot in general format code inside a macro invocation. If it defaulted to formatting as if it were ordinary Rust, it could misformat other, macro-specific syntax. So it's a limitation in rustfmt itself that's hard to solve, unfortunately.

See also: https://github.com/rust-lang/rustfmt#limitations

**Comment by jacobdeichert** [comment]
Thanks for confirming @ijks, I started figuring that was the case.

No need to keep this open any longer then 👍
