### ISSUE TITLE
Any plan to add 'let' or 'subject'

### ISSUE THREAD

**Issue by ms-ati** [utkarshkukreti/speculate.rs#5]
Would it be possible to have an analog to the 'let' and 'subject' features of RSpec, which are lazy and memoized within each test example? In RSpec, this allows nested contexts to override just a single bit of test setup which can be referred to by other test setup?

**Comment by utkarshkukreti** [comment]
I don't think this is possible without an extra dependency (or unsafe code). I'd suggest using [`lazy-static`](https://github.com/rust-lang-nursery/lazy-static.rs) and declare static variables inside the `describe`/`context` blocks. Declaring them there will not inject a copy of it in every test; they'll only be defined once.

```
describe "foo" {
    lazy_static! {
        static ref THREE: u32 = { 1 + 2 }
    }
    test "bar" {
        assert_eq(THREE, 3);
    }
}
```

What do you think?

**Comment by ms-ati** [comment]
Ah that may work. Thanks for this response! Let's see if we have a set of nested `lazy_static!` that refer to each other, can the same name be overridden in a deeper `context` and only have the change there? That's the way `let` and `subject` are used best in RSpec

**Comment by ms-ati** [comment]
@utkarshkukreti the approach you suggested above doesn't seem to work -- am getting the following compile error:

```
error[E0369]: binary operation `==` cannot be applied to type `speculate::__::foo::THREE`
  --> tests/first_spec.rs:28:13
   |
28 |             assert_eq!(THREE, 3);
   |             ^^^^^^^^^^^^^^^^^^^^^
   |
   = note: an implementation of `std::cmp::PartialEq` might be missing for `speculate::__::foo::THREE`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

**Comment by ms-ati** [comment]
For extra goodness, the `-Z` advice also doesn't appear to work

**Comment by ms-ati** [comment]
Got it, here's a fixed version of your example above, with the missing **deref** that was not indicated at all:

```rust
describe "foo" {
    lazy_static! {
        static ref THREE: u32 = { 1 + 2 }
    }
    test "bar" {
        assert_eq(*THREE, 3);
    }
}
```

So, now that this compiles: let's see if this is a viable way to override the lazy values in nested contexts. By they way, how can we refer to the version of the same name defined above (as in `super()` calls in Ruby RSpec's `let` and `subject`)?

**Comment by ms-ati** [comment]
Unfortunately, this approach doesn't appear to work for overriding the values in deeper nested scopes:

```rust
#![feature(plugin)]
#![plugin(speculate)]
#[macro_use]
extern crate lazy_static;

speculate! {
    fn add(a: i32, b: i32) -> i32 {
        a + b
    }

    describe "add" {
        lazy_static! {
            static ref SUBJECT: i32 = { add(*A, *B) };
        }

        lazy_static! {
            static ref A: i32 = { 1 };
        }

        lazy_static! {
            static ref B: i32 = { 1 };
        }

        it "returns 2" {
            assert_eq!(*SUBJECT, 2);
        }

        context "when A is zero" {
            lazy_static! {
                static ref A: i32 = { 0 };
            }

            it "returns B" {
                assert_eq!(*SUBJECT, *B);
            }
        }
    }
}
```

This gives compiles error:

```
$ cargo test
   Compiling artsy v0.1.0 (file:///Users/msiegel/Documents/workspace/Riverdale/artsy)
warning: static item is never used: `A`
  --> tests/first_spec.rs:34:13
   |
34 | /             lazy_static! {
35 | |                 static ref A: i32 = { 0 };
36 | |             }
   | |_____________^
   |
   = note: #[warn(dead_code)] on by default
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

**Comment by utkarshkukreti** [comment]
(Was waiting for #6 to fix itself before looking into this.)

Yes, you cannot override a value like this because `SUBJECT`, `A`, and `B` are defined in a parent scope. What you can do for this particular case is to define `SUBJECT` inside a `before`:

    describe "add" {
        before {
            lazy_static! {
                static ref SUBJECT: i32 = { add(*A, *B) };
            }
        }

        lazy_static! {
            static ref A: i32 = { 1 };
        }

        lazy_static! {
            static ref B: i32 = { 1 };
        }
        ...

This will inject a copy of the declaration of `SUBJECT` into each `test`/`it` block and it'll access the closest `A` and `B` in the scope.

> By they way, how can we refer to the version of the same name defined above (as in super() calls in Ruby RSpec's let and subject)?

I'm not sure I understand this. Can you give an example?

**Comment by ms-ati** [comment]
Thanks *so much* @utkarshkukreti for your engagement with my questions on this ticket. I'm grateful for your time and knowledge!

> > By they way, how can we refer to the version of the same name defined above (as in super() calls in Ruby RSpec's let and subject)?
> 
> I'm not sure I understand this. Can you give an example?

Well, what I'm looking to achieve are, in the style of Ruby's RSpec, a series of *nested contexts* where various assumptions are overridden, and different expectations are made.

For example, if we start with your last example of putting the `lazy_static!` in the `before` block:

```rust
describe "add" {
    before {
        lazy_static! {
            static ref SUBJECT: i32 = { add(*A, *B) };
        }
    }

    lazy_static! {
        static ref A: i32 = { 1 };
    }

    lazy_static! {
        static ref B: i32 = { 1 };
    }

    it "returns 2" {
        assert_eq!(*SUBJECT, 2);
    }

    # setup a nested context that changes an assumption
    
    context "when parameter A is zero" {
        lazy_static! {
            static ref A: i32 = { 0 };
        }

        it "returns parameter B" {
            assert_eq!(*SUBJECT, *B);
        }
    }
}
```

Is the above possible? 

In Ruby, one could even refer to the "parent" scope value of A when redefining it in a context, for example:

```ruby
subject { add(a, b) }
let(:a) { 1 }
let(:b) { 1 }
let(:expected_result) { 2 }

it { is_expected.to eq(expected_result) }

context "when a is incremented by 1" do
  let(:a) { super() + 1 }
  let(:expected_result) { super() + 1 }
  it { is_expected.to eq(expected_result) }
end
```

Do the above questions make sense?

**Comment by utkarshkukreti** [comment]
> Is the above possible?

That code works for me. Are you getting any errors?

> In Ruby, one could even refer to the "parent" scope value of A when redefining it in a context, for example:

So, `super::_` will work but only for lazy statics defined outside any block. The code in `before` (and `after`) blocks is literally copied into every test code and so don't have a super definition. Here's an example:

```rust
#![feature(plugin)]
#![plugin(speculate)]
#[macro_use]
extern crate lazy_static;

speculate! {
    describe "add" {
        lazy_static! {
            static ref A: i32 = { 1 };
        }

        context "when parameter A is zero" {
            lazy_static! {
                static ref A: i32 = { 0 };
            }

            it "..." {
                assert_eq!(*A, 0);
                assert_eq!(*super::A, 1);
            }
        }
    }
}
```

**Comment by utkarshkukreti** [comment]
Closing for now but let me know if you still have any questions!
