### ISSUE TITLE
Allow arbitrarily naming generated modules

### ISSUE THREAD

**Issue by 6A** [utkarshkukreti/speculate.rs#7]
I'd like to segment my tests into multiple sections of a file. For example, a structure would be defined, and then some tests related to this structure would appear in a `speculate!` block, and another structure would appear, etc. This would look like this:

```rust
pub struct Foo(...);

speculate! {
    it "can do things" {
        // Test Foo here.
    }
}

pub struct Bar(...);

speculate! {
    it "can do other things" {
        // Test Bar here.
    }
}
```

However, `speculate` always generate a module named `speculate`, which causes conflicts at the top-level.

The current workaround is to put every `speculate` macro in a individual, private modules, but it adds an unnecessary layer of nesting.

Instead, it would be nice if one of the following syntaxes would be added:

```rust
speculate! module_name { }
speculate! "module_name" { }
```

or if `speculate` appended, for example, the current line number to the created module name.

**Comment by utkarshkukreti** [comment]
I'm not sure if it's possible to add an optional identifier after the macro name. Stainless only allows `describe!` macro with an identifier while speculate doesn't allow anything.

If adding this feature doesn't break the existing macro (i.e. both `speculate! {}` and `speculate! something {}` work), I'd be happy to merge the feature and release it. I currently do not have time to work on features though.

If you want to give it a shot, [here's](https://github.com/reem/stainless/blob/master/src/lib.rs#L187-L192) how stainless' macro is registered.

**Comment by 6A** [comment]
It looks like `IdentTT` might get deprecated, which means that what I wanted may not be possible. However, I came up with another solution, which is to prefix the position of the character at which the `speculate` block begins. I also removed the `__` module, which gives us an output like this:

```
     Running target\debug\deps\basic.exe

running 7 tests
test ec3::speculate #1359::foo ... ok
test ec5::speculate #1468::foo ... ok
test speculate #75::something::works at level 2 after context! ... ok
test speculate #75::something::works at level 2! ... ok
test speculate #75::works at level 1 after describe! ... ok
test speculate #75::works at level 1! ... ok
test speculate #75::something::nested::works at level 3! ... ok

test result: ok. 7 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

instead of 

```
     Running target\debug\deps\basic.exe

running 7 tests
test ec3::speculate::__::foo ... ok
test ec5::speculate::__::foo ... ok
test speculate::__::something::works at level 2 after context! ... ok
test speculate::__::something::works at level 2! ... ok
test speculate::__::works at level 1 after describe! ... ok
test speculate::__::works at level 1! ... ok
test speculate::__::something::nested::works at level 3! ... ok

test result: ok. 7 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

It's a little ugly, but it does the job.

**Comment by utkarshkukreti** [comment]
That sounds good. What do you think about using the line number instead of character index? It would also help the user figure out which speculate block failed. I'd be happy to merge a PR and make a new release!

**Comment by 6A** [comment]
The line number was what I initially wanted to use, but it does not seem to be available to compiler plugins (at least not in the APIs I looked at, it might have changed since the previous versions of Rust).

**Comment by utkarshkukreti** [comment]
Ah. Could you send a PR since you already have this implemented? I'll see if I can find a workaround for the line # or else probably just go with the character number for now.
