### ISSUE TITLE
Switch to proc_macro

### ISSUE THREAD

**Issue by utkarshkukreti** [utkarshkukreti/speculate.rs#8]
https://github.com/rust-lang/rust/issues/38356

It's going to be stable soon. Finally we can stop chasing changes in the private rustc crates' APIs. Probably a good time to bump to v1.0.0 at the same time.

**Comment by 6A** [comment]
Furthermore, `proc_macro` has the span data needed to make #7 use line numbers instead of character indices.

**Comment by utkarshkukreti** [comment]
This will need to happen sometime soon. As soon as https://github.com/rust-lang/rust/pull/51285 is merged, speculate will stop working. A temporary fix would be to replace the uses of `quote` macros with the AST generation functions.

**Comment by utkarshkukreti** [comment]
I think that for now we should just replace the `quote` macros with the rustc API so it doesn't break when that PR is merged. It would be cool to have this run on stable Rust at some point though.

**Comment by 6A** [comment]
I continued working on it, and I think we should definitely use [proc-macro2](https://crates.io/crates/proc-macro2) and [quote](https://crates.io/crates/quote), which make it much easier.

**Comment by 6A** [comment]
I did some more digging, and also discovered [syn](https://github.com/dtolnay/syn). Would you mind adding another dependency to it? It seems it would make the parsing logic much easier to handle, even though it's not very complicated to start with.
