### ISSUE TITLE
How to use ![should_panic] or ![ignore] with speculate?

### ISSUE THREAD

**Issue by svenstaro** [utkarshkukreti/speculate.rs#9]
Basically as the title says, how do I use those special attributes to ignore some tests?

**Comment by utkarshkukreti** [comment]
You can now!

https://github.com/utkarshkukreti/speculate.rs/commit/abc1a4f020221b04c1fa0166fe64696cfad2f17b#diff-04c6e90faac2675aa89e2176d2eec7d8R51

**Comment by svenstaro** [comment]
That's super sweet! Thanks.
